### ISSUE TITLE
Figure labels / references do not work

### ISSUE THREAD

**Issue by ratnanil** [tauvinia/Project_PTED_Group2#1]
Your figure references do not work (see screenshot) 

![image](https://github.com/tauvinia/Project_PTED_Group2/assets/12532091/8e469f45-08eb-4454-974a-b6989eb7319a)

The reason is, that the cell metadata must be on the first lines of the chunk. So rather than writing:

````
```{r}
## Plot

#| fig-cap: "Duration of drives"
#| label: fig-duration
boxplot(duration_from_home$difftime, duration_from_hadiko$difftime,
        main = "Duration per Drive",
        las = 2,
        col = c("steelblue4", "darkred"),
        ylab = "Minutes",
        xlab = "Startpoint",
        names = c("Home", "Hadiko")
)
```
````

it should be:

````
```{r}
#| fig-cap: "Duration of drives"
#| label: fig-duration
boxplot(duration_from_home$difftime, duration_from_hadiko$difftime,
        main = "Duration per Drive",
        las = 2,
        col = c("steelblue4", "darkred"),
        ylab = "Minutes",
        xlab = "Startpoint",
        names = c("Home", "Hadiko")
)
```
````

**Comment by tauvinia** [comment]
Hello Nils,
thank you for the tipp! I was trying to solve it yesterday but didn't manage, so decided to give it in like it is. And the solution was so easy... So now it should work!

**Comment by ratnanil** [comment]
perfect!
